export const SET_TOKEN = 'SET_TOKEN';
export const SET_USER = 'SET_USER';
export const SET_ALL_TODOS = "SET_ALL_TODOS";
export const SET_ONE_TODO = "SET_ONE_TODO";
export const SET_FINISHED_TODOS = "SET_FINISHED_TODOS";
export const SET_UNFINISHED_TODOS = "SET_UNFINISHED_TODOS";
export const SET_DELETE_TODO = "SET_DELETE_TODO";
export const SET_ONE_TODO_UPDATE = "SET_ONE_TODO_UPDATE";